version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Jaypatil25"
    labels:
      - "dependencies"
      - "client"
    commit-message:
      prefix: "chore(client):"
      prefix-development: "chore(client-dev):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Jaypatil25"
    labels:
      - "dependencies"
      - "server"
    commit-message:
      prefix: "chore(server):"
      prefix-development: "chore(server-dev):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "Jaypatil25"
    labels:
      - "ci"
      - "github-actions"
    commit-message:
      prefix: "ci:"
      include: "scope"
